### ISSUE TITLE
Apply module `jest-express` for app-use statements and further use cases 

### ISSUE THREAD

**Issue by brunolnetto** [trouchet/sappio#61]
__Motivation__: There is the module [`jest-express`](https://www.npmjs.com/package/jest-express) for express-based NodeJS web applications. The current author failed to apply it for incompetence. However, someone must do it! 

__Issue__: Investigate and apply module `jest-express` on the current repository to cover middleware calls and other silently covered code lines. 

__Suggestion__: Apply `jest-express` built-in concepts to use this app boilerplate. The repository has a reasonably comprehensible structure that organizes, equips, and builds the app in file [/main/src/core/utils/app.js](https://github.com/trouchet/sappio/blob/main/src/core/utils/app.js).  

__Suggested contributors__: @jameswlane

**Comment by brunolnetto** [comment]
__Update__: I was able to apply an [example here](https://github.com/trouchet/sappio/blob/main/src/core/__test__/server.test.js) by server start use-case.

**Comment by jameswlane** [comment]
I will try and look at the test this week. See if I can see why it's not working. From what I can see, it should work.

**Comment by brunolnetto** [comment]
@jameswlane I will be very glad if you could make a repositour and contribute with your knowledge in `jest-express`. The resulting repository will be available as an open-source project.

**Comment by brunolnetto** [comment]
@jameswlane in the meanwhile, I was able to make _almost_ 💯 % coverage. 😀  You can investigate further, but it does not seem an issue anymore.
